* Author: Patrick Earl
* Creation: 03/17/2021
* Class: CSC223
* Purpose: **See Below**

# Pandas HW3 Example

This is an example of completing the requirements for homework 3 with just using pandas. 

This will import the *netflix_titles.csv* as a Pandas **DataFrame**.

In [1]:
import pandas as pd
import numpy as np

In [12]:
# This will import the csv file into a dataframe called netflix
netflix = pd.read_csv('netflix_titles.csv', index_col=0)

In [3]:
netflix.head(10)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
s6,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,"July 1, 2017",2016,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Mysteries",A genetics professor experiments with a treatm...
s7,Movie,122,Yasir Al Yasiri,"Amina Khalil, Ahmed Dawood, Tarek Lotfy, Ahmed...",Egypt,"June 1, 2020",2019,TV-MA,95 min,"Horror Movies, International Movies","After an awful accident, a couple admitted to ..."
s8,Movie,187,Kevin Reynolds,"Samuel L. Jackson, John Heard, Kelly Rowan, Cl...",United States,"November 1, 2019",1997,R,119 min,Dramas,After one of his high school students attacks ...
s9,Movie,706,Shravan Kumar,"Divya Dutta, Atul Kulkarni, Mohan Agashe, Anup...",India,"April 1, 2019",2019,TV-14,118 min,"Horror Movies, International Movies","When a doctor goes missing, his psychiatrist w..."
s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,"December 15, 2017",2008,TV-MA,143 min,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...

In [4]:
tv_show = netflix[netflix['type'] == "TV Show"]
# del tv_show['type']
# del tv_show['release_year']
tv_show = tv_show[['title', 'director', 'country', 'date_added', 'duration']]
tv_show['duration'] = tv_show['duration'].str.split(' ').str[0]
tv_show['duration'] = tv_show['duration'].astype('int64')

In [5]:
tv_show.dtypes

title         object
director      object
country       object
date_added    object
duration       int64
dtype: object

In [6]:
tv_show.sort_values('duration', ascending=False, inplace=True)

In [11]:
tv_show.to_json('netflix_shows2.json', indent=4, orient='records')

In [10]:
tv_show.head()

,title,director,country,date_added,duration
show_id,,,,,
s2539,Grey's Anatomy,NaN,United States,"May 9, 2020",16
s4439,NCIS,NaN,United States,"July 1, 2018",15
s5913,Supernatural,Phil Sgriccia,"United States, Canada","June 5, 2020",15
s1472,COMEDIANS of the world,NaN,United States,"January 1, 2019",13
s5138,Red vs. Blue,NaN,United States,NaN,13