# This is a markdown cell

You can use *markdown* to **format** the text within. Use the *GitHub Markdown Cheatsheet* 
You could also use [This Markdown Tutorial](https://www.markdowntutorial.com/) to learn more

This is an example showing how to complete homework 3 using just pandas. 

1. Import *netflix_titles.csv* file into a dataframe.
    * Make *show_id* the index using `index_col`. 
2. Create a new dataframe of *just* TV shows.
3. Remove the extra columns to keep only *title, director, country, date_added, and duration*.
4. Convert duration to a int for sorting
5. Sort the tv_shows dataframe using `sort_values()`
6. Export it to json

In [1]:
import pandas as pd
import numpy as np

In [2]:
# This will open the the netflix_titles.csv file and make it a dataframe
netflix = pd.read_csv('netflix_titles.csv', index_col='show_id')

In [3]:
netflix.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [4]:
tv_shows = netflix[netflix['type'] == 'TV Show']
tv_shows = tv_shows[['title', 'director', 'country', 'date_added', 'duration']]

In [5]:
tv_shows.head()

,title,director,country,date_added,duration
show_id,,,,,
s1,3%,NaN,Brazil,"August 14, 2020",4 Seasons
s6,46,Serdar Akar,Turkey,"July 1, 2017",1 Season
s12,1983,NaN,"Poland, United States","November 30, 2018",1 Season
s13,1994,Diego Enrique Osorno,Mexico,"May 17, 2019",1 Season
s17,Feb-09,NaN,NaN,"March 20, 2019",1 Season

In [6]:
tv_shows['duration'] = tv_shows['duration'].str.split(' ').str[0]
tv_shows['duration'] = tv_shows['duration'].astype('int64')

In [7]:
tv_shows.dtypes

title         object
director      object
country       object
date_added    object
duration       int64
dtype: object

In [8]:
tv_show = tv_shows.sort_values('duration', ascending=False)

In [9]:
tv_show.to_json('netflix_shows.json', indent=4, orient='records')